### 회원 정보 조회
GET localhost:8080/valid/users/4

### 회원 정보 등록(valid)
POST localhost:8080/valid/users
Content-Type: application/json

{
  "id": "id",
  "pwd": "pwd",
  "name": "코알라",
  "enrollDate": "2025-04-24"
}